---
title: "project565"
author: "Arisara Kanaprasertkul"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data setup}
www = "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2010.csv"
Tennis = read.csv(www)
i=11
for(i in 11:20){
  
  www = paste("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_20",as.character(i),".csv",sep = "")
  temp = read.csv(www)
  Tennis = rbind(Tennis, temp)
}
```

```{r data org}
library(stringr)
library(tidyverse)
top3 <- c("Novak Djokovic","Rafael Nadal","Roger Federer")
tennis3 <- filter(Tennis, str_detect(winner_name, paste(top3, collapse="|")))
bp <- Tennis %>% group_by(winner_name)%>%summarize(total_wins = n())
bp = tail(bp[order(bp$total_wins),],10)
par(las=2, mar = c(4,14,4,4));barplot(bp$total_wins,names.arg = bp$winner_name, horiz=T, xlim = c(0,700))
```

```{r data aggregation- don't use}

bp2=tennis3; bp2$year = as.numeric(substring(bp2$tourney_date, 1, 4))
bp3 = bp2 %>% group_by(winner_name, year)%>%summarise(wins = n())
bp3 = as.matrix(spread(bp3, year, wins)[,2:12])
rownames(bp3) =c("Novak Djokovic","Rafael Nadal","Roger Federer")
par(las=2, mar = c(4,14,4,4));barplot(t(bp3)[,c(3,2,1)],horiz=T, col=colors()[c(23,81,85,22,21,89,88,20,87,6)] , 
        border="white", 
        space=0.04, 
        font.axis=2, 
        xlab="Wins over years 2010-2020")

sum(complete.cases(tennis3))
nrow(tennis3)

#tennis3 <- na.omit(tennis3)


tennis3$time <- as.numeric(substring(tennis3$tourney_date, 1, 4)) + 0.25*(ceiling(as.numeric(substring(tennis3$tourney_date, 5, 6))/3))

total_w <- tennis3 %>% group_by(winner_name, time)%>%summarize(total_wins = n())
qtr = expand.grid(time = seq(2010.25,2020.75, 0.25 ),winner_name = top3)
top3_aggr = left_join(qtr,total_w)

```

```{r explore}
djokovic  = subset(top3_aggr, winner_name == "Novak Djokovic")
nadal  = subset(top3_aggr, winner_name == "Rafael Nadal")
federer  = subset(top3_aggr, winner_name == "Roger Federer")
df = data.frame(time = djokovic$time, djo.win = djokovic$total_wins, nad.win = nadal$total_wins, fed.win = federer$total_wins)
library("imputeTS")
df = na_replace(df, 0.1)
ts.df = ts(df,start = 2010.00, end = 2020.50, fr = 4)
ts.df = na_replace(ts.df, 0.1)
ts.plot(djo=ts.df[,"djo.win"],nad=ts.df[,"nad.win"],fed=ts.df[,"fed.win"],lty=c(1:3), col = c("red","blue","green"), ylab= "Wins");  legend("topright", legend = c("Djokovic","Nadal","Federer"), lty=c(1:3), col = c("red","blue","green"))
#djo
plot(ts.df[,"djo.win"])
plot(density(df$djo.win))
boxplot(df$djo.win)
plot(decompose(ts.df[,"djo.win"]))
acf(ts.df[,"djo.win"])
pacf(ts.df[,"djo.win"])

#nad
plot(ts.df[,"nad.win"])
plot(density(df$nad.win))
boxplot(df$nad.win)
plot(decompose(ts.df[,"nad.win"]))
acf(ts.df[,"nad.win"])
pacf(ts.df[,"nad.win"])

#fed
plot(ts.df[,"fed.win"])
plot(density(df$fed.win))
boxplot(df$fed.win)
plot(decompose(ts.df[,"fed.win"]))
acf(ts.df[,"fed.win"])
pacf(ts.df[,"fed.win"])
```

```{r Djokovic Regression & VAR, eval=FALSE, include=FALSE}
## DJOKOVIC
adf.test(ts.df[,"djo.win"]) 
po.test(ts.df[,2:4])


djo.lm <- lm(ts.df[,"djo.win"])
summary(djo.lm)

djo.res <- resid(djo.lm)
acf(djo.res) 
pacf(djo.res)


library(vars)
djo.var <- VAR(ts.df[1:37,2], p = 3, type = "trend")
coef(djo.var)
acf(resid(djo.var)[, 1]) 

djo.pred <- predict(djo.var, n.ahead = 6)
djo.pred
djoWin.pred <- ts(djo.pred$fcst$djo.win[, 1], st = 2019.50, fr = 4)
ts.plot(cbind(ts.df[,"djo.win"], djoWin.pred), lty = c(1,9), col=c("black","red") )
mape.djo.var = mean(abs(ts.df[38:43,"djo.win"] - djoWin.pred)/ts.df[38:43,"djo.win"])

```

```{r Nadal Regression & VAR, eval=FALSE, include=FALSE}
adf.test(ts.df[,"nad.win"]) 
adf.test(ts.df[,"nad.ace"]) 
adf.test(ts.df[,"nad.bps"]) 


po.test(ts.df[,5:7])


nad.lm <- lm(ts.df[,"nad.win"] ~ ts.df[,"nad.ace"] + ts.df[,"nad.bps"])
summary(nad.lm)

nad.res <- resid(nad.lm)
acf(nad.res) 
pacf(nad.res)



library(vars)
nad.var <- VAR(ts.df[1:37,5:7], p = 3, type = "trend")
coef(nad.var)
acf(resid(nad.var)[, 1]) 
acf(resid(nad.var)[, 2]) 
acf(resid(nad.var)[, 3]) 

nad.pred <- predict(nad.var, n.ahead = 6)
nad.pred
nadWin.pred <- ts(nad.pred$fcst$nad.win[, 1], st = 2019.50, fr = 4)
nadAces.pred <- ts(nad.pred$fcst$nad.ace[, 1], st = 2019.50, fr = 4)
nadBP.pred <- ts(nad.pred$fcst$nad.bps[, 1], st = 2019.50, fr = 4)
ts.plot(cbind(ts.df[,"nad.win"], nadWin.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(ts.df[,"nad.ace"], nadAces.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(ts.df[,"nad.bps"], nadBP.pred), lty = c(1,9), col=c("black","red") )
mape.nad.var = mean(abs(ts.df[38:43,"nad.win"] - nadWin.pred)/ts.df[38:43,"nad.win"])


```

```{r Federer Regression & VAR, eval=FALSE, include=FALSE}
adf.test(ts.df[,"fed.win"]) 
adf.test(ts.df[,"fed.ace"]) 
adf.test(ts.df[,"fed.bps"])

po.test(ts.df[,8:10])


fed.lm <- lm(ts.df[,"fed.win"] ~ ts.df[,"fed.ace"] + ts.df[,"fed.bps"])
summary(fed.lm)

fed.res <- resid(fed.lm)
acf(fed.res) 
pacf(fed.res)


library(vars)
fed.var <- VAR(ts.df[1:37,8:10], p = 3, type = "trend")
coef(fed.var)
acf(resid(fed.var)[, 1]) 
acf(resid(fed.var)[, 2]) 
acf(resid(fed.var)[, 3]) 

fed.pred <- predict(fed.var, n.ahead = 6)
fed.pred
fedWin.pred <- ts(fed.pred$fcst$fed.win[, 1], st = 2019.50, fr = 4)
fedAces.pred <- ts(fed.pred$fcst$fed.ace[, 1], st = 2019.50, fr = 4)
fedBP.pred <- ts(fed.pred$fcst$fed.bps[, 1], st = 2019.50, fr = 4)
ts.plot(cbind(ts.df[,"fed.win"], fedWin.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(ts.df[,"fed.ace"], fedAces.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(ts.df[,"fed.bps"], fedBP.pred), lty = c(1,9), col=c("black","red") )
mape.fed.var = mean(abs(ts.df[38:43,"fed.win"] - fedWin.pred)/ts.df[38:43,"fed.win"])

```

```{r regression, eval=FALSE, include=FALSE}
# We test if the ts variables are stationary before applying linear regression model
library(tseries)
adf_result = data.frame(t(sapply(apply(ts.df[,2:10], 2, adf.test),c)))
#we see that all the time series variables in ts.df are stationary
lm_djo = lm(ts.df[,2] ~ ts.df[,3]+ts.df[,4])
summary(lm_djo)
lm_nad = lm(ts.df[,5] ~ ts.df[,6]+ts.df[,7])
summary(lm_nad)
lm_fed = lm(ts.df[,8] ~ ts.df[,9]+ts.df[,10])
summary(lm_fed)
```

```{r djo ariMA}
#djo
plot(ts.df[,"djo.win"])
djo.pre = window(ts.df[,"djo.win"],2010.00,2019.00)
djo.post = window(ts.df[,"djo.win"],2019.25,2020.50)
#djo.post[5] = 0.1
acf(ts.df[,"djo.win"])
pacf(ts.df[,"djo.win"])
#Arima
get.best.arima <- function(x.ts, maxord = c(1,1,1))
{
  best.aic <- Inf
  n <- length(x.ts)
  for (p in 0:maxord[1]) for(d in 0:maxord[2]) for(q in 0:maxord[3])
    {
      fit <- arima(x.ts, order = c(p,d,q))
      fit.aic <- AIC(fit)
      if (fit.aic < best.aic)
      {
        best.aic <- fit.aic
        best.fit <- fit
        best.model <- c(p,d,q)
      }
    }
  list(best.aic, best.fit, best.model)
}

best.arima.djo<- get.best.arima(djo.pre, maxord = c(2,2,2))
best.fit.djo <- best.arima.djo[[2]]
acf( resid(best.fit.djo) )
best.arima.djo [[3]]
djo.pred = predict(best.fit.djo,6)$pred

ts.plot(cbind(djo.pre, djo.pred, djo.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.djo.arima_211 = mean(abs(djo.post - djo.pred)/djo.post)
mape = matrix(data = NA,9,7, dimnames = list(c("DJO_HW","DJO_ARMA","DJO_SARIMA","NAD_HW","NAD_ARMA","NAD_SARIMA","FED_HW","FED_ARMA","FED_SARIMA"),c("ME","RMSE","MAE","MPE","MAPE","ACF1","Theil's U")))
library(forecast)
mape["DJO_ARMA",]=accuracy(djo.pred,djo.post)
```



```{r nad ariMA}
#nad
plot(ts.df[,"nad.win"])
nad.pre = window(ts.df[,"nad.win"],2010.00,2019.00)
nad.post = window(ts.df[,"nad.win"],2019.25,2020.50)
#nad.post[5] = 0.1
acf(ts.df[,"nad.win"])
pacf(ts.df[,"nad.win"])
#Arima

best.arima.nad<- get.best.arima(nad.pre, maxord = c(0,2,1))
best.fit.nad <- best.arima.nad[[2]]
acf( resid(best.fit.nad) )
best.arima.nad [[3]]
nad.pred = predict(best.fit.nad,6)$pred

ts.plot(cbind(nad.pre, nad.pred, nad.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.nad.arima_011 = mean(abs(nad.post - nad.pred)/nad.post)
mape["NAD_ARMA",]=accuracy(nad.pred,nad.post)
```

```{r fed ariMA}
#fed
plot(ts.df[,"fed.win"])
fed.pre = window(ts.df[,"fed.win"],2010.00,2018.50)
fed.post = window(ts.df[,"fed.win"],2018.75,2020.00)

acf(ts.df[,"fed.win"])
pacf(ts.df[,"fed.win"])
#Arima

best.arima.fed<- get.best.arima(fed.pre, maxord = c(2,2,2))
best.fit.fed <- best.arima.fed[[2]]
acf( resid(best.fit.fed) )
best.arima.fed [[3]]
fed.pred = predict(best.fit.fed,6)$pred

ts.plot(cbind(fed.pre, fed.pred, fed.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.fed.arima_011 = mean(abs(fed.post - fed.pred)/fed.post)
mape["FED_ARMA",]=accuracy(fed.pred,fed.post)
```
```{r djo sariMA}
#djo
#sArima
get.best.sarima <- function(x.ts, maxord = c(1,1,1,1,1,1))
{
  best.aic <- Inf
  n <- length(x.ts)
  for (p in 0:maxord[1]) for(d in 0:maxord[2]) for(q in 0:maxord[3])
    for (P in 0:maxord[4]) for(D in 0:maxord[5]) for(Q in 0:maxord[6])
    {
      fit <- arima(x.ts, order = c(p,d,q),
                   seas = list(order = c(P,D,Q),
                               frequency(x.ts)), method = "CSS")
      
      fit.aic <- -2 * fit$loglik + (log(n) + 1) * length(fit$coef)
      
      if (fit.aic < best.aic)
      {
        best.aic <- fit.aic
        best.fit <- fit
        best.model <- c(p,d,q,P,D,Q)
      }
    }
  list(best.aic, best.fit, best.model)
}

#djo
best.sarima.djo<- get.best.sarima(djo.pre, maxord = c(2,2,2,2,2,2))
best.fits.djo <- best.sarima.djo[[2]]
acf( resid(best.fits.djo) )
best.sarima.djo [[3]]
djo.preds = predict(best.fits.djo,6)$pred

ts.plot(cbind(djo.pre, djo.preds, djo.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.djo.sarima = mean(abs(djo.post - djo.preds)/djo.post)
library(forecast)
mape["DJO_SARIMA",] = accuracy(djo.preds,djo.post)

#nad
best.sarima.nad<- get.best.sarima(nad.pre, maxord = c(2,2,2,2,2,2))
best.fits.nad <- best.sarima.nad[[2]]
acf( resid(best.fits.nad) )
best.sarima.nad [[3]]
nad.preds = predict(best.fits.nad,6)$pred

ts.plot(cbind(nad.pre, nad.preds, nad.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.nad.sarima_211 = mean(abs(nad.post - nad.preds)/nad.post)
mape["NAD_SARIMA",] = accuracy(nad.preds,nad.post)

#fed
best.sarima.fed<- get.best.sarima(fed.pre, maxord = c(2,2,2,2,2,2))
best.fits.fed <- best.sarima.fed[[2]]
acf( resid(best.fits.fed) )
best.sarima.fed [[3]]
fed.preds = predict(best.fits.fed,6)$pred

ts.plot(cbind(fed.pre, fed.preds, fed.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.fed.sarima_211 = mean(abs(fed.post - fed.preds)/fed.post)
mape["FED_SARIMA",] = accuracy(fed.preds,fed.post)
```

```{r HoltWinters s-m}
djo.hw = HoltWinters(djo.pre, seasonal = "m")
djo.forc = predict(djo.hw,n.ahead = 6)
ts.plot(cbind(djo.pre, djo.forc, djo.post), lty = c(1,9,2), col=c("black","red","blue") )
mape["DJO_HW",] = accuracy(djo.forc,djo.post)
mape.djo.hw = mean(abs(djo.post - djo.forc)/djo.post)
#nad
nad.hw = HoltWinters(nad.pre, seasonal = "m")
nad.forc = predict(nad.hw,n.ahead = 6)
ts.plot(cbind(nad.pre, nad.forc, nad.post), lty = c(1,9,2), col=c("black","red","blue") )
mape["NAD_HW",] = accuracy(nad.forc,nad.post)
mape.nad.hw = mean(abs(nad.post - nad.forc)/nad.post)
#fed
fed.hw = HoltWinters(fed.pre, seasonal = "m")
fed.forc = predict(fed.hw,n.ahead = 6)
ts.plot(cbind(fed.pre, fed.forc, fed.post), lty = c(1,9,2), col=c("black","red","blue") )
mape["FED_HW",] = accuracy(fed.forc,fed.post)
mape.fed.hw = mean(abs(fed.post - fed.forc)/fed.post)
```


```{r result}
barplot(mape[,"RMSE"],col=colors()[c(21,81,21,21,81,21,21,81,21)])
ts.plot(cbind(ts.df[,"djo.win"],ts.df[,"nad.win"],ts.df[,"fed.win"],djo.pred,nad.pred,fed.pred,djo.preds,nad.preds,fed.preds,djo.forc,nad.forc,fed.forc), lty = c(1,1,1,9,9,9,2,2,2,3,3,3), col=c("black","red","blue","black","red","blue","black","red","blue","black","red","blue") )

ts.plot(cbind(ts.df[,"djo.win"],djo.pred,djo.preds,djo.forc), lty = c(1,2,9,3), col=c("black","green","red","blue"), main = "Djokovic Wins forecast" ); legend("topleft", legend = c("Real-world","ARIMA_211","SARIMA","HoltWinters"), lty=c(1,2,9,3), col = c("black","green","red","blue"))

ts.plot(cbind(ts.df[,"nad.win"],nad.pred,nad.preds,nad.forc), lty = c(1,2,9,3), col=c("black","green","red","blue"),main = "Nadal Wins forecast" ); legend("topleft", legend = c("Real-world","ARIMA_011","SARIMA","HoltWinters"), lty=c(1,2,9,3), col = c("black","green","red","blue"))

ts.plot(cbind(ts.df[,"fed.win"],fed.pred,fed.preds,fed.forc), lty = c(1,2,9,3), col=c("black","green","red","blue") ,main = "Federer Wins forecast"); legend("topleft", legend = c("Real-world","ARIMA_011","SARIMA","HoltWinters"), lty=c(1,2,9,3), col = c("black","green","red","blue"))

fed.pred1 = predict(best.fit.fed,8)$pred

ts.plot(cbind(djo.pred,nad.pred,fed.pred1[3:8]), lty = c(1,2,9), col=c("green","red","blue") ,main = "Winner"); legend("topleft", legend = c("Djokovic","Nadal","Federer"), lty=c(1,2,9), col = c("green","red","blue"))

sum(djo.pred)
sum(nad.pred)
sum(fed.pred)

t.test(djo.pred, nad.pred)
```

```{r 2021}
djo.2021 = predict(arima(ts.df[,"djo.win"], order = c(2,1,1)),4)$pred
nad.2021 = predict(arima(ts.df[,"nad.win"], order = c(0,1,1)),4)$pred
fed.2021 = predict(arima(ts.df[,"fed.win"], order = c(0,1,1)),4)$pred

ts.plot(cbind(djo.2021,nad.2021,fed.2021), lty = c(1,2,9), col=c("green","red","blue") ,main = "Winner"); legend("topright", legend = c("Djokovic","Nadal","Federer"), lty=c(1,2,9), col = c("green","red","blue"))

t.test(djo.2021, nad.2021)

```

```{r dVn}
ts.dvn = ts.df[,"djo.win"]-ts.df[,"nad.win"]
ts.plot(ts.dvn)
plot(decompose(ts.dvn))
dvn.pre = window(ts.dvn,2010.00,2019.00)
dvn.post = window(ts.dvn,2019.25,2020.50)

#HW
dvn.hw = HoltWinters(dvn.pre, seasonal = "a")
dvn.forc = predict(dvn.hw,n.ahead = 6)
ts.plot(cbind(dvn.pre, dvn.forc, dvn.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.dvn.hw = mean(abs(dvn.post - dvn.forc)/dvn.post)
accuracy(dvn.forc, dvn.post)

#Arima
best.arima.dvn<- get.best.arima(dvn.pre, maxord = c(0,2,1))
best.fit.dvn <- best.arima.dvn[[2]]
acf( resid(best.fit.dvn) )
best.arima.dvn [[3]]
dvn.pred = predict(best.fit.dvn,6)$pred

ts.plot(cbind(dvn.pre, dvn.pred, dvn.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.dvn.arima_011 = mean(abs(dvn.post - dvn.pred)/dvn.post)
accuracy(dvn.pred, dvn.post)

#sarima
best.sarima.dvn<- get.best.sarima(dvn.pre, maxord = c(2,2,2,2,2,2))
best.fits.dvn <- best.sarima.dvn[[2]]
acf( resid(best.fits.dvn) )
best.sarima.dvn [[3]]
dvn.preds = predict(best.fits.dvn,6)$pred
ts.plot(cbind(dvn.pre, dvn.preds, dvn.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.dvn.sarima_211 = mean(abs(dvn.post - dvn.preds)/dvn.post)
accuracy(dvn.preds,dvn.post)

dvn.2021 = predict(HoltWinters(ts.dvn, seasonal = "a"),n.ahead = 4)
zero = dvn.2021
zero[1:4]=0
t.test(dvn.2021, zero)
ts.plot(cbind(ts.dvn, dvn.2021), lty = c(1,9), col=c("black","blue"), main= "Difference in number of wins for Djokovic and Nadal (Holtwinters)" )

```

