---
title: "project565"
author: "Arisara Kanaprasertkul"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data setup}
www = "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2010.csv"
Tennis = read.csv(www)
i=11
for(i in 11:20){
  
  www = paste("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_20",as.character(i),".csv",sep = "")
  temp = read.csv(www)
  Tennis = rbind(Tennis, temp)
}
```

```{r data org}
library(stringr)
library(tidyverse)
top3 <- c("Novak Djokovic","Rafael Nadal","Roger Federer")
tennis3 <- filter(Tennis, str_detect(winner_name, paste(top3, collapse="|")))
```

```{r data aggregation- don't use}

tennis3 <- na.omit(tennis3)

tennis3$time <- as.numeric(substring(tennis3$tourney_date, 1, 4)) + 0.25*(ceiling(as.numeric(substring(tennis3$tourney_date, 5, 6))/3))

total_w <- tennis3 %>% group_by(winner_name, time)%>%
  summarize(total_wins = n(),
            total_win_aces = mean(w_ace),
            total_win_bpSaved = mean(w_bpSaved))
qtr = expand.grid(time = seq(2010.25,2020.75, 0.25 ),winner_name = top3)
top3_aggr = left_join(qtr,total_w)
```

```{r explore}
djokovic  = subset(top3_aggr, winner_name == "Novak Djokovic")
nadal  = subset(top3_aggr, winner_name == "Rafael Nadal")
federer  = subset(top3_aggr, winner_name == "Roger Federer")
df = data.frame(time = djokovic$time, djo.win = djokovic$total_wins, djo.ace = djokovic$total_win_aces, djo.bps = djokovic$total_win_bpSaved, nad.win = nadal$total_wins, nad.ace = nadal$total_win_aces, nad.bps = nadal$total_win_bpSaved, fed.win = federer$total_wins, fed.ace = federer$total_win_aces, fed.bps = federer$total_win_bpSaved)
df = na_replace(df, 0)
ts.df = ts(df,start = 2010.25, end = 2020.75, fr = 4)
library("imputeTS")
ts.df = na_replace(ts.df, 0)

#djo
plot(ts.df[,"djo.win"])
plot(density(df$djo.win))
boxplot(df$djo.win,df$djo.ace,df$djo.bps)
library(corrplot)
library(car)
scatterplotMatrix(df[,2:4])

cor1 <- cor(df[,2:4])
round(cor1, 2)
corrplot(cor1)

plot(decompose(ts.df[,"djo.win"]))
acf(ts.df[,"djo.win"])
pacf(ts.df[,"djo.win"])

#nad
plot(ts.df[,"nad.win"])
plot(density(df$nad.win))
boxplot(df$nad.win,df$nad.ace,df$nad.bps)
scatterplotMatrix(df[,5:7])

cor1 <- cor(df[,5:7])
round(cor1, 2)
corrplot(cor1)

plot(decompose(ts.df[,"nad.win"]))
acf(ts.df[,"nad.win"])
pacf(ts.df[,"nad.win"])

#fed
plot(ts.df[,"fed.win"])
plot(density(df$fed.win))
boxplot(df$fed.win,df$fed.ace,df$fed.bps)
scatterplotMatrix(df[,8:10])

cor1 <- cor(df[,8:10])
round(cor1, 2)
corrplot(cor1)

plot(decompose(ts.df[,"fed.win"]))
acf(ts.df[,"fed.win"])
pacf(ts.df[,"fed.win"])
```

```{r Djokovic Regression & VAR}
## DJOKOVIC
adf.test(ts.df[,"djo.win"]) #djokovicWinner_ts is stationary
adf.test(ts.df[,"djo.ace"]) #djokovicWinAces_ts is stationary
adf.test(ts.df[,"djo.bps"]) #also stationary
# When two variables are stationary, linear regression model is appropriate. VAR can also be used.

po.test(ts.df[,2:4])
# The Phillips-Ouliaris test shows there is evidence that the series are cointegrated, which justifies the use of a regression model.
# The two variables contain common stochastic trends.

djo.lm <- lm(ts.df[,"djo.win"] ~ ts.df[,"djo.ace"] + ts.df[,"djo.bps"])
summary(djo.lm)
## If Djokovic increases his Ace by 1, his winner would go up by 0.42.
#djo.lm2 <- lm(djokovicFinal$Wins ~ djokovicFinal$BreakPointsSaved)
#summary(djo.lm2)
## If Djokovic increases his number of BPsaved in the month by 1, his winner would go up by 0.51.
djo.res <- resid(djo.lm)
acf(djo.res) # white noise which means model is a good fit
pacf(djo.res)
#djo.res2 <- resid(djo.lm2)
#acf(djo.res2) # white noise which means model is a good fit
#pacf(djo.res2)


library(vars)
djo.var <- VAR(ts.df[,2:4], p = 3, type = "trend")
coef(djo.var)
acf(resid(djo.var)[, 1]) #white noise
acf(resid(djo.var)[, 2]) #white noise
acf(resid(djo.var)[, 3]) #white noise
# this confirms that this is a good model to use
djo.pred <- predict(djo.var, n.ahead = 4)
djo.pred
djoWin.pred <- ts(djo.pred$fcst$djo.win[, 1], st = 2021, fr = 4)
djoAces.pred <- ts(djo.pred$fcst$djo.ace[, 1], st = 2021, fr = 4)
djoBP.pred <- ts(djo.pred$fcst$djo.bps[, 1], st = 2021, fr = 4)
ts.plot(cbind(window(ts.df[,"djo.win"], start = 2010), djoWin.pred), lty = 1:2)
ts.plot(cbind(window(ts.df[,"djo.ace"], start = 2010), djoAces.pred), lty = 1:2)
ts.plot(cbind(window(ts.df[,"djo.bps"], start = 2010), djoBP.pred), lty = 1:2)

```

```{r Federer Regression & VAR}


```

```{r Nadal Regression & VAR}

```

```{r regression}
# We test if the ts variables are stationary before applying linear regression model
library(tseries)
adf_result = data.frame(t(sapply(apply(ts.df[,2:10], 2, adf.test),c)))
#we see that all the time series variables in ts.df are stationary
lm_djo = lm(ts.df[,2] ~ ts.df[,3]+ts.df[,4])
summary(lm_djo)
lm_nad = lm(ts.df[,5] ~ ts.df[,6]+ts.df[,7])
summary(lm_nad)
lm_fed = lm(ts.df[,8] ~ ts.df[,9]+ts.df[,10])
summary(lm_fed)
```

```{r djo ariMA}
#djo
plot(ts.df[,"djo.win"])
djo.pre = window(ts.df[,"djo.win"],2010.25,2019.25)
djo.post = window(ts.df[,"djo.win"],2019.50,2020.75)
djo.post[5] = 0.1

#Arima
get.best.arima <- function(x.ts, maxord = c(1,1,1))
{
  best.aic <- Inf
  n <- length(x.ts)
  for (p in 0:maxord[1]) for(d in 0:maxord[2]) for(q in 0:maxord[3])
    {
      fit <- arima(x.ts, order = c(p,d,q))
      fit.aic <- AIC(fit)
      if (fit.aic < best.aic)
      {
        best.aic <- fit.aic
        best.fit <- fit
        best.model <- c(p,d,q)
      }
    }
  list(best.aic, best.fit, best.model)
}

best.arima.djo<- get.best.arima(djo.pre, maxord = c(2,2,2))
best.fit.djo <- best.arima.djo[[2]]
acf( resid(best.fit.djo) )
best.arima.djo [[3]]
djo.pred = predict(best.fit.djo,6)$pred

ts.plot(cbind(djo.pre, djo.pred, djo.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.djo.arima_011 = mean(abs(djo.post - djo.pred)/djo.post)

```

```{r nad ariMA}
#nad
plot(ts.df[,"nad.win"])
nad.pre = window(ts.df[,"nad.win"],2010.25,2019.25)
nad.post = window(ts.df[,"nad.win"],2019.50,2020.75)
nad.post[5] = 0.1
acf(ts.df[,"nad.win"])
pacf(ts.df[,"nad.win"])
#Arima
get.best.arima <- function(x.ts, maxord = c(1,1,1))
{
  best.aic <- Inf
  n <- length(x.ts)
  for (p in 0:maxord[1]) for(d in 0:maxord[2]) for(q in 0:maxord[3])
    {
      fit <- arima(x.ts, order = c(p,d,q))
      fit.aic <- AIC(fit)
      if (fit.aic < best.aic)
      {
        best.aic <- fit.aic
        best.fit <- fit
        best.model <- c(p,d,q)
      }
    }
  list(best.aic, best.fit, best.model)
}

best.arima.nad<- get.best.arima(nad.pre, maxord = c(2,2,2))
best.fit.nad <- best.arima.nad[[2]]
acf( resid(best.fit.nad) )
best.arima.nad [[3]]
nad.pred = predict(best.fit.nad,6)$pred

ts.plot(cbind(nad.pre, nad.pred, nad.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.nad.arima_202 = mean(abs(nad.post - nad.pred)/nad.post)

```

```{r fed ariMA}
#fed
plot(ts.df[,"fed.win"])
fed.pre = window(ts.df[,"fed.win"],2010.25,2018.75)
fed.post = window(ts.df[,"fed.win"],2019.00,2020.25)

acf(ts.df[,"fed.win"])
pacf(ts.df[,"fed.win"])
#Arima
get.best.arima <- function(x.ts, maxord = c(1,1,1))
{
  best.aic <- Inf
  n <- length(x.ts)
  for (p in 0:maxord[1]) for(d in 0:maxord[2]) for(q in 0:maxord[3])
    {
      fit <- arima(x.ts, order = c(p,d,q))
      fit.aic <- AIC(fit)
      if (fit.aic < best.aic)
      {
        best.aic <- fit.aic
        best.fit <- fit
        best.model <- c(p,d,q)
      }
    }
  list(best.aic, best.fit, best.model)
}

best.arima.fed<- get.best.arima(fed.pre, maxord = c(2,2,2))
best.fit.fed <- best.arima.fed[[2]]
acf( resid(best.fit.fed) )
best.arima.fed [[3]]
fed.pred = predict(best.fit.fed,6)$pred

ts.plot(cbind(fed.pre, fed.pred, fed.post), lty = c(1,9,2), col=c("black","red","blue") )
mape.fed.arima_011 = mean(abs(fed.post - fed.pred)/fed.post)

```
