---
title: "project565"
author: "Arisara Kanaprasertkul"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data setup}
www = "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2010.csv"
Tennis = read.csv(www)
i=11
for(i in 11:20){
  
  www = paste("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_20",as.character(i),".csv",sep = "")
  temp = read.csv(www)
  Tennis = rbind(Tennis, temp)
}
```

```{r data org}
library(stringr)
library(tidyverse)
top3 <- c("Novak Djokovic","Rafael Nadal","Roger Federer")
tennis3 <- filter(Tennis, str_detect(winner_name, paste(top3, collapse="|"))|str_detect(loser_name, paste(top3, collapse="|")))
#top10 <- c("Novak Djokovic","Rafael Nadal","Roger Federer","Andy Murray","David Ferrer","Jo Wilfried Tsonga","Tomas Berdych","Mardy Fish","Janko Tipsarevic","Nicolas Almagro")
#tennis10 <- filter(Tennis, str_detect(winner_name, paste(top10, collapse="|"))|str_detect(loser_name, paste(top10, collapse="|")))

```

```{r data aggregation- don't use}

tennis3 <- na.omit(tennis3)

tennis3$year <- as.numeric(substring(tennis3$tourney_id, 1, 4))
tennis3$month <- as.numeric(substring(tennis3$tourney_date, 5, 6))
tennis3$grandslam <- ifelse(tennis3$tourney_level == "G", "grandslam", "non-grandslam")

total_wins <- tennis3 %>% group_by(winner_name, year, month, surface, grandslam)%>%
  summarize(total_wins = n(),
            total_win_rounds = mean(round),
            total_win_aces = sum(w_ace),
            total_win_df = sum(w_df),
            total_win_svpt = mean(w_svpt),
            total_win_1stIn = mean(w_1stIn),
            total_win_1stWon = mean(w_1stWon),
            total_win_2ndWon = mean(w_2ndWon),
            total_win_bpSaved = sum(w_bpSaved),
            total_win_bpFaced = sum(w_bpFaced))

total_loses <- tennis3 %>% group_by(loser_name, year, month, surface, grandslam)%>%
  summarize(total_loses = n(),
            total_lose_rounds = mean(round),
            total_lose_aces = sum(l_ace),
            total_lose_df = sum(l_df),
            total_lose_svpt = mean(l_svpt),
            total_lose_1stIn = mean(l_1stIn),
            total_lose_1stWon = mean(l_1stWon),
            total_lose_2ndWon = mean(l_2ndWon),
            total_lose_bpSaved = sum(l_bpSaved),
            total_lose_bpFaced = sum(l_bpFaced))

total_wins$concat <- paste(total_wins$winner_name, total_wins$year, total_wins$surface, total_wins$grandslam, sep="_")
total_loses$concat <- paste(total_loses$loser_name, total_loses$year, total_loses$surface, total_loses$grandslam, sep="_")

top_3_wins <- total_wins %>% filter(winner_name %in% top3)
top_3_loses <- total_loses %>% filter(loser_name %in% top3)

#colnames(top_3_wins)[1] <- "name"
#colnames(top_3_loses)[1] <- "name"

top3_aggregated <- left_join(top_3_wins,top_3_loses, by= "concat")
```

```{r}
total_w <- tennis3 %>% group_by(winner_name, year, month)%>%
  summarize(total_wins = n(),
            total_win_rounds = mean(round),
            total_win_aces = mean(w_ace),
            total_win_df = mean(w_df),
            total_win_svpt = mean(w_svpt),
            total_win_1stIn = mean(w_1stIn),
            total_win_1stWon = mean(w_1stWon),
            total_win_2ndWon = mean(w_2ndWon),
            total_win_bpSaved = mean(w_bpSaved),
            total_win_bpFaced = mean(w_bpFaced),
            duration_win = mean(minutes))

total_l <- tennis3 %>% group_by(loser_name, year, month)%>%
  summarize(total_loses = n(),
            total_lose_rounds = mean(round),
            total_lose_aces = sum(l_ace),
            total_lose_df = sum(l_df),
            total_lose_svpt = mean(l_svpt),
            total_lose_1stIn = mean(l_1stIn),
            total_lose_1stWon = mean(l_1stWon),
            total_lose_2ndWon = mean(l_2ndWon),
            total_lose_bpSaved = sum(l_bpSaved),
            total_lose_bpFaced = sum(l_bpFaced))

total_w$concat <- paste(total_w$winner_name, total_w$year, total_w$month, sep="_")
total_l$concat <- paste(total_l$loser_name, total_l$year,  total_l$month, sep="_")

top_3_w <- total_w %>% filter(winner_name %in% top3)
top_3_l <- total_l %>% filter(loser_name %in% top3)

#colnames(top_3_wins)[1] <- "name"
#colnames(top_3_loses)[1] <- "name"

top3_aggr <- left_join(top_3_w,top_3_l, by= "concat")
```

```{r Djokovic TS}
djokovic  = subset(top3_aggr, winner_name == "Novak Djokovic")
library(zoo)
djokovic$date <- as.Date(with(djokovic, paste(year.x, month.x, "01", sep = "-")), "%Y-%m-%d")
date.month= data.frame(date = seq(as.Date("2010-01-01"), length=132, by="months"),winner_name = "Novak Djokovic")

djokovic_withdate <- left_join(date.month,djokovic)
summary(djokovic_withdate)

djokovic_withdate[, 5]

library("imputeTS")
djokovic_withdate <- na_replace(djokovic_withdate, 0.01)
djokovicWinner_ts <- ts(djokovic_withdate[,5], start = 2010, freq = 12)
djokovicWinAces_ts <- ts(djokovic_withdate[,7], start = 2010, freq = 12)
djokovicWinDF_ts <- ts(djokovic_withdate[,8], start = 2010, freq = 12)
djokovicWinSVPT_ts <- ts(djokovic_withdate[,9], start = 2010, freq = 12)
djokovicWin1stIn_ts <- ts(djokovic_withdate[,10], start = 2010, freq = 12)
djokovicWin1stWon_ts <- ts(djokovic_withdate[,11], start = 2010, freq = 12)
djokovicWin2ndWon_ts <- ts(djokovic_withdate[,12], start = 2010, freq = 12)
djokovicWinBPSaved_ts <- ts(djokovic_withdate[,13], start = 2010, freq = 12)
djokovicWinBPFaced_ts <- ts(djokovic_withdate[,14], start = 2010, freq = 12)
djokovicDuration_ts <- ts(djokovic_withdate[,15], start = 2010, freq = 12)

#plot(djokovic_ts)

combinedData.djokovic <- data.frame(djokovic_withdate$date, djokovicWinner_ts, djokovicWinAces_ts, djokovicWinDF_ts, djokovicWinSVPT_ts, djokovicWin1stIn_ts, djokovicWin1stWon_ts, djokovicWin2ndWon_ts, djokovicWinBPSaved_ts, djokovicWinBPFaced_ts, djokovicDuration_ts)
colnames(combinedData.djokovic) <- c("Date", "Wins", "Aces", "Doublefaults", "ServePoints", "FirstServeIn", "FirstServeWon", "SecondServeWon", "BreakPointsSaved", "BreakPointsFaced", "Duration")
head(combinedData.djokovic)

plot(density(combinedData.djokovic$Wins))

boxplot(combinedData.djokovic$Wins,combinedData.djokovic$Aces, combinedData.djokovic$Doublefaults, combinedData.djokovic$ServePoints, combinedData.djokovic$Duration)
install.packages("corrplot")
library(corrplot)
library(car)
scatterplotMatrix(combinedData.djokovic[3:11])

cor1 <- cor(combinedData.djokovic[3:11])
round(cor1, 2)

corrplot(cor1)


# Dropping FirstServeIn, FirstServeWon, SecondServeWon since they are highlu correlated to ServePoints
# and dropping BreakpointsFaced since it is highly correlated to BreakPointsSaved

djokovicFinal <- select(combinedData.djokovic, Date, Wins, Aces, Doublefaults, ServePoints, BreakPointsSaved,Duration)

cor2 <- cor(djokovicFinal[3:7])
round(cor2, 2)

corrplot(cor2)

plot(decompose(djokovicFinal$Wins))
acf(djokovicFinal$Wins)# Looks like we have AR(1)
pacf(djokovicFinal$Wins)# First lag looks significant
```


```{r Nadal TS}
nadal  = subset(top3_aggr, winner_name == "Rafael Nadal")
library(zoo)
nadal$date <- as.Date(with(nadal, paste(year.x, month.x, "01", sep = "-")), "%Y-%m-%d")
date.month= data.frame(seq(as.Date("2010-01-01"), length=132, by="months"))
colnames(date.month)[1] <- "date"
nadal_withdate <- left_join(date.month,nadal, by="date")
summary(nadal_withdate)

nadal_withdate[, 5]

library("imputeTS")
nadal_withdate <- na_replace(nadal_withdate, 0.01)
nadalWinner_ts <- ts(nadal_withdate[,5], start = 2010, freq = 12)
nadalWinAces_ts <- ts(nadal_withdate[,7], start = 2010, freq = 12)
nadalWinDF_ts <- ts(nadal_withdate[,8], start = 2010, freq = 12)
nadalWinSVPT_ts <- ts(nadal_withdate[,9], start = 2010, freq = 12)
nadalWin1stIn_ts <- ts(nadal_withdate[,10], start = 2010, freq = 12)
nadalWin1stWon_ts <- ts(nadal_withdate[,11], start = 2010, freq = 12)
nadalWin2ndWon_ts <- ts(nadal_withdate[,12], start = 2010, freq = 12)
nadalWinBPSaved_ts <- ts(nadal_withdate[,13], start = 2010, freq = 12)
nadalWinBPFaced_ts <- ts(nadal_withdate[,14], start = 2010, freq = 12)
nadalDuration_ts <- ts(nadal_withdate[,15], start = 2010, freq = 12)

#plot(nadal_ts)

combinedData.nadal <- data.frame(nadal_withdate$date, nadalWinner_ts, nadalWinAces_ts, nadalWinDF_ts, nadalWinSVPT_ts, nadalWin1stIn_ts, nadalWin1stWon_ts, nadalWin2ndWon_ts, nadalWinBPSaved_ts, nadalWinBPFaced_ts, nadalDuration_ts)
colnames(combinedData.nadal) <- c("Date", "Wins", "Aces", "Doublefaults", "ServePoints", "FirstServeIn", "FirstServeWon", "SecondServeWon", "BreakPointsSaved", "BreakPointsFaced", "Duration")
head(combinedData.nadal)

plot(density(combinedData.nadal$Wins))

boxplot(combinedData.nadal$Wins,combinedData.nadal$Aces, combinedData.nadal$Doublefaults, combinedData.nadal$ServePoints)
#install.packages("corrplot")
library(corrplot)
library(car)
scatterplotMatrix(combinedData.nadal[3:11])

cor1 <- cor(combinedData.nadal[3:11])
round(cor1, 2)

library(corrplot)
corrplot(cor1)


# Dropping FirstServeIn, FirstServeWon, SecondServeWon since they are highlu correlated to ServePoints
# and dropping BreakpointsFaced since it is highly correlated to BreakPointsSaved

library(dplyr)
nadalFinal <- select(combinedData.nadal, Date, Wins, Aces, Doublefaults, ServePoints, BreakPointsSaved, Duration)

cor2 <- cor(nadalFinal[3:7])
round(cor2, 2)

corrplot(cor2)

plot(decompose(nadalFinal$Wins))
acf(nadalFinal$Wins)# Looks like we have AR(1)
pacf(nadalFinal$Wins)# First lag looks significant
```


```{r Federer TS}
federer  = subset(top3_aggr, winner_name == "Roger Federer")
library(zoo)
federer$date <- as.Date(with(federer, paste(year.x, month.x, "01", sep = "-")), "%Y-%m-%d")
date.month= data.frame(seq(as.Date("2010-01-01"), length=132, by="months"))
colnames(date.month)[1] <- "date"
federer_withdate <- left_join(date.month,federer, by="date")
summary(federer_withdate)

federer_withdate[, 5]

library("imputeTS")
federer_withdate <- na_replace(federer_withdate, 0.01)
federerWinner_ts <- ts(federer_withdate[,5], start = 2010, freq = 12)
federerWinAces_ts <- ts(federer_withdate[,7], start = 2010, freq = 12)
federerWinDF_ts <- ts(federer_withdate[,8], start = 2010, freq = 12)
federerWinSVPT_ts <- ts(federer_withdate[,9], start = 2010, freq = 12)
federerWin1stIn_ts <- ts(federer_withdate[,10], start = 2010, freq = 12)
federerWin1stWon_ts <- ts(federer_withdate[,11], start = 2010, freq = 12)
federerWin2ndWon_ts <- ts(federer_withdate[,12], start = 2010, freq = 12)
federerWinBPSaved_ts <- ts(federer_withdate[,13], start = 2010, freq = 12)
federerWinBPFaced_ts <- ts(federer_withdate[,14], start = 2010, freq = 12)
federerDuration_ts <- ts(federer_withdate[,15], start = 2010, freq = 12)

#plot(federer_ts)

combinedData.federer <- data.frame(federer_withdate$date, federerWinner_ts, federerWinAces_ts, federerWinDF_ts, federerWinSVPT_ts, federerWin1stIn_ts, federerWin1stWon_ts, federerWin2ndWon_ts, federerWinBPSaved_ts, federerWinBPFaced_ts, federerDuration_ts)
colnames(combinedData.federer) <- c("Date", "Wins", "Aces", "Doublefaults", "ServePoints", "FirstServeIn", "FirstServeWon", "SecondServeWon", "BreakPointsSaved", "BreakPointsFaced", "Duration")
head(combinedData.federer)

plot(density(combinedData.federer$Wins))

boxplot(combinedData.federer$Wins,combinedData.federer$Aces, combinedData.federer$Doublefaults, combinedData.federer$ServePoints)
#install.packages("corrplot")
#library(corrplot)
scatterplotMatrix(combinedData.federer[3:11])

cor1 <- cor(combinedData.federer[3:11])
round(cor1, 2)

corrplot(cor1)


# Dropping FirstServeIn, FirstServeWon, SecondServeWon since they are highlu correlated to ServePoints
# and dropping BreakpointsFaced since it is highly correlated to BreakPointsSaved

federerFinal <- select(combinedData.federer, Date, Wins, Aces, Doublefaults, ServePoints, BreakPointsSaved, Duration)

cor2 <- cor(federerFinal[3:7])
round(cor2, 2)

corrplot(cor2)

plot(decompose(federerFinal$Wins))
acf(federerFinal$Wins)# Looks like we have AR(1)
pacf(federerFinal$Wins)# First lag looks significant
```


```{r Train vs. Test}

djokovic.train <- djokovicFinal[1:66,]
djokovic.test <- djokovicFinal[67:132,]

nadal.train <- nadalFinal[1:66,]
nadal.test <- nadalFinal[67:132,]

federer.train <- federerFinal[1:66,]
federer.test <- federerFinal[67:132,]


```



```{r Arima Model}
set.seed(2021)
library(forecast)
arima.fit.djokovic <- Arima(ts(djokovic.train[2]), order = c(1,1,0))
set.seed(2021)
arima.auto.fit <- auto.arima(ts(train[2]), approximation = FALSE, stepwise = FALSE)




```



```{r Djokovic Regression & VAR}
## DJOKOVIC
adf.test(djokovicWinner_ts) #djokovicWinner_ts is stationary
adf.test(djokovicWinAces_ts) #djokovicWinAces_ts is stationary
adf.test(djokovicWinBPSaved_ts) #also stationary
# When two variables are stationary, linear regression model is appropriate. VAR can also be used.

po.test(cbind(djokovicWinner_ts, djokovicWinAces_ts, djokovicWinBPSaved_ts))
# The Phillips-Ouliaris test shows there is evidence that the series are cointegrated, which justifies the use of a regression model.
# The two variables contain common stochastic trends.

djo.lm <- lm(djokovicFinal$Wins ~ djokovicFinal$Aces + djokovicFinal$BreakPointsSaved)
summary(djo.lm)
## If Djokovic increases his Ace by 1, his winner would go up by 0.42.
#djo.lm2 <- lm(djokovicFinal$Wins ~ djokovicFinal$BreakPointsSaved)
#summary(djo.lm2)
## If Djokovic increases his number of BPsaved in the month by 1, his winner would go up by 0.51.
djo.res <- resid(djo.lm)
acf(djo.res) # white noise which means model is a good fit
pacf(djo.res)
#djo.res2 <- resid(djo.lm2)
#acf(djo.res2) # white noise which means model is a good fit
#pacf(djo.res2)


library(vars)
djo.var <- VAR(cbind(djokovicWinner_ts, djokovicWinAces_ts, djokovicWinBPSaved_ts), p = 3, type = "trend")
coef(djo.var)
acf(resid(djo.var)[, 1]) #white noise
acf(resid(djo.var)[, 2]) #white noise
acf(resid(djo.var)[, 3]) #white noise
# this confirms that this is a good model to use
djo.pred <- predict(djo.var, n.ahead = 12)
djo.pred
djoWin.pred <- ts(djo.pred$fcst$djokovicWinner_ts[, 1], st = 2021, fr = 12)
djoAces.pred <- ts(djo.pred$fcst$djokovicWinAces_ts[, 1], st = 2021, fr = 12)
djoBP.pred <- ts(djo.pred$fcst$djokovicWinBPSaved_ts[, 1], st = 2021, fr = 12)
ts.plot(cbind(window(djokovicWinner_ts, start = 2010), djoWin.pred), lty = 1:2)
ts.plot(cbind(window(djokovicWinAces_ts, start = 2010), djoAces.pred), lty = 1:2)
ts.plot(cbind(window(djokovicWinBPSaved_ts, start = 2010), djoBP.pred), lty = 1:2)


```
```{r mape}
djo.var <- VAR(cbind(djokovicWinner_ts[1:120], djokovicWinAces_ts[1:120], djokovicWinBPSaved_ts[1:120]), p = 3, type = "trend")
coef(djo.var)
acf(resid(djo.var)[, 1]) #white noise
acf(resid(djo.var)[, 2]) #white noise
acf(resid(djo.var)[, 3]) #white noise
# this confirms that this is a good model to use
djo.pred <- predict(djo.var, n.ahead = 12)
djo.pred
djoWin.pred <- ts(djo.pred$fcst$y1[, 1], st = 2020, fr = 12)
djoAces.pred <- ts(djo.pred$fcst$y2[, 1], st = 2020, fr = 12)
djoBP.pred <- ts(djo.pred$fcst$y3[, 1], st = 2020, fr = 12)
ts.plot(cbind(djokovicWinner_ts, djoWin.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(djokovicWinAces_ts, djoAces.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(djokovicWinBPSaved_ts, djoBP.pred), lty = c(1,9), col=c("black","red") )
mape.djo.var = mean(abs(djokovicWinner_ts[121:132] - djoWin.pred)/djokovicWinner_ts[121:132])

#nadal
nad.var <- VAR(cbind(nadalWinner_ts[1:120], nadalWinAces_ts[1:120], nadalWinBPSaved_ts[1:120]), p = 3, type = "trend")
coef(nad.var)
acf(resid(nad.var)[, 1]) #white noise
acf(resid(nad.var)[, 2]) #white noise
acf(resid(nad.var)[, 3]) #white noise
# this confirms that this is a good model to use
nad.pred <- predict(nad.var, n.ahead = 12)
nad.pred
nadWin.pred <- ts(nad.pred$fcst$y1[, 1], st = 2020, fr = 12)
nadAces.pred <- ts(nad.pred$fcst$y2[, 1], st = 2020, fr = 12)
nadBP.pred <- ts(nad.pred$fcst$y3[, 1], st = 2020, fr = 12)
ts.plot(cbind(nadalWinner_ts, nadWin.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(nadalWinAces_ts, nadAces.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(nadalWinBPSaved_ts, nadBP.pred), lty = c(1,9), col=c("black","red") )
mape.nad.var = mean(abs(nadalWinner_ts[121:132] - nadWin.pred)/nadalWinner_ts[121:132])

#feder
fed.var <- VAR(cbind(federerWinner_ts[1:120], federerWinAces_ts[1:120], federerWinBPSaved_ts[1:120]), p = 3, type = "trend")
coef(fed.var)
acf(resid(fed.var)[, 1]) #white noise
acf(resid(fed.var)[, 2]) #white noise
acf(resid(fed.var)[, 3]) #white noise
# this confirms that this is a good model to use
fed.pred <- predict(fed.var, n.ahead = 12)
fed.pred
fedWin.pred <- ts(fed.pred$fcst$y1[, 1], st = 2020, fr = 12)
fedAces.pred <- ts(fed.pred$fcst$y2[, 1], st = 2020, fr = 12)
fedBP.pred <- ts(fed.pred$fcst$y3[, 1], st = 2020, fr = 12)
ts.plot(cbind(federerWinner_ts, fedWin.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(federerWinAces_ts, fedAces.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(federerWinBPSaved_ts, fedBP.pred), lty = c(1,9), col=c("black","red") )
mape.fed.var = mean(abs(federerWinner_ts[121:132] - fedWin.pred)/federerWinner_ts[121:132])
```

```{r Federer Regression & VAR}
## FEDERER
adf.test(federerWinner_ts) #federerWinner_ts is stationary
adf.test(federerWinAces_ts) #federerWinAces_ts is stationary
adf.test(federerWinDF_ts) #also stationary
adf.test(federerWinBPSaved_ts) #also stationary
# When two variables are stationary, linear regression model is appropriate. VAR can also be used.
po.test(cbind(federerWinner_ts, federerWinAces_ts, federerWinBPSaved_ts))
# The Phillips-Ouliaris test shows there is evidence that the series are cointegrated, which justifies the use of a regression model.
# The variables contain common stochastic trends.

fed.lm <- lm(federerFinal$Wins ~ federerFinal$Aces + federerFinal$BreakPointsSaved)
summary(fed.lm)
## If federer increases his Ace by 1, his winner would go up by 0.42.
#fed.lm2 <- lm(federerFinal$Wins ~ federerFinal$BreakPointsSaved)
#summary(fed.lm2)
## If federer increases his number of BPsaved in the month by 1, his winner would go up by 0.51.
fed.res <- resid(fed.lm)
acf(fed.res) # white noise which means model is a good fit
pacf(fed.res)
#fed.res2 <- resid(fed.lm2)
#acf(fed.res2) # white noise which means model is a good fit
#pacf(fed.res2)


library(vars)
fed.var <- VAR(cbind(federerWinner_ts, federerWinAces_ts, federerWinBPSaved_ts), p = 3, type = "trend")
coef(fed.var)
acf(resid(fed.var)[, 1]) #white noise
acf(resid(fed.var)[, 2]) #white noise
acf(resid(fed.var)[, 3]) #white noise
# this confirms that this is a good model to use
fed.pred <- predict(fed.var, n.ahead = 12)
fed.pred
fedWin.pred <- ts(fed.pred$fcst$federerWinner_ts[, 1], st = 2021, fr = 12)
fedAces.pred <- ts(fed.pred$fcst$federerWinAces_ts[, 1], st = 2021, fr = 12)
fedBP.pred <- ts(fed.pred$fcst$federerWinBPSaved_ts[, 1], st = 2021, fr = 12)
ts.plot(cbind(window(federerWinner_ts, start = 2010), fedWin.pred), lty = 1:2)
ts.plot(cbind(window(federerWinAces_ts, start = 2010), fedAces.pred), lty = 1:2)
ts.plot(cbind(window(federerWinBPSaved_ts, start = 2010), fedBP.pred), lty = 1:2)


```

```{r Nadal Regression & VAR}
## NADAL
adf.test(nadalWinner_ts) #nadalWinner_ts is stationary
adf.test(nadalWinAces_ts) #nadalWinAces_ts is stationary
adf.test(nadalWinBPSaved_ts) #also stationary
# When two variables are stationary, linear regression model is appropriate. VAR can also be used.
po.test(cbind(nadalWinner_ts, nadalWinAces_ts, nadalWinBPSaved_ts))
# The Phillips-Ouliaris test shows there is evidence that the series are cointegrated, which justifies the use of a regression model.
# The two variables contain common stochastic trends.


nad.lm <- lm(nadalFinal$Wins ~ nadalFinal$Aces + nadalFinal$BreakPointsSaved)
summary(nad.lm)
## If nadal increases his Ace by 1, his winner would go up by 0.42.
#nad.lm2 <- lm(nadalFinal$Wins ~ nadalFinal$BreakPointsSaved)
#summary(nad.lm2)
## If nadal increases his number of BPsaved in the month by 1, his winner would go up by 0.51.
nad.res <- resid(nad.lm)
acf(nad.res) # white noise which means model is a good fit
pacf(nad.res)
#nad.res2 <- resid(nad.lm2)
#acf(nad.res2) # white noise which means model is a good fit
#pacf(nad.res2)


library(vars)
nad.var <- VAR(cbind(nadalWinner_ts, nadalWinAces_ts, nadalWinBPSaved_ts), p = 3, type = "trend")
coef(nad.var)
acf(resid(nad.var)[, 1]) #white noise
acf(resid(nad.var)[, 2]) #white noise
acf(resid(nad.var)[, 3]) #white noise
# this confirms that this is a good model to use
nad.pred <- predict(nad.var, n.ahead = 12)
nad.pred
nadWin.pred <- ts(nad.pred$fcst$nadalWinner_ts[, 1], st = 2021, fr = 12)
nadAces.pred <- ts(nad.pred$fcst$nadalWinAces_ts[, 1], st = 2021, fr = 12)
nadBP.pred <- ts(nad.pred$fcst$nadalWinBPSaved_ts[, 1], st = 2021, fr = 12)
ts.plot(cbind(window(nadalWinner_ts, start = 2010), nadWin.pred), lty = 1:2)
ts.plot(cbind(window(nadalWinAces_ts, start = 2010), nadAces.pred), lty = 1:2)
ts.plot(cbind(window(nadalWinBPSaved_ts, start = 2010), nadBP.pred), lty = 1:2)




```

```{r regression}
ts.df = ts(cbind(djo=djokovicFinal[,2:6],nad=nadalFinal[,2:6],fed=federerFinal[,2:6]), start = c(substr(range(djokovicFinal$Date)[1],1,4),substr(range(djokovicFinal$Date)[1],6,7)), end=c(substr(range(djokovicFinal$Date)[2],1,4),substr(range(djokovicFinal$Date)[2],6,7)), frequency = 12)
# We test if the ts variables are stationary before applying linear regression model
library(tseries)
adf_result = data.frame(t(sapply(apply(ts.df, 2, adf.test),c)))
#we see that all the time series variables in ts.df are stationary
lm_djo = lm(ts.df[,1] ~ ts.df[,2]+ts.df[,3]+ts.df[,4]+ts.df[,5])
summary(lm_djo)
lm_nad = lm(ts.df[,6] ~ ts.df[,7]+ts.df[,8]+ts.df[,9]+ts.df[,10])
summary(lm_nad)
lm_fed = lm(ts.df[,11] ~ ts.df[,12]+ts.df[,13]+ts.df[,14]+ts.df[,15])
summary(lm_fed)
```

```{r ariMA}
plot(ts.df[,1])
djo.pre = window(ts.df[,1],c(2010,1),c(2019,12))
djo.post = window(ts.df[,1],c(2020,1),c(2020,12))

Time = time(djo.pre)
Seas = factor(cycle(djo.pre))

djo.lm = lm(djo.pre ~ 0 + Time + Seas)
coef(djo.lm)

pred.Time = seq(2020, length=12, by=1/12)
pred.Seas = factor(c(1,2,3,4,5,6,7,8,9,10,11,12))
pred.data = data.frame(Time=pred.Time,Seas=pred.Seas)
pred.data

pred.djo.lm = predict(djo.lm, pred.data)
pred.djo.lm

djo.lm.resid<-djo.lm$residuals
acf(djo.lm.resid)
pacf(djo.lm.resid)

best.order = c(0, 0, 0)
best.aic = Inf
for (i in 0:3) for (j in 0:3) {
  fit.aic = AIC(arima(djo.lm.resid, order = c(i,0,j)))
  if (fit.aic < best.aic) {
    best.order = c(i, 0, j)
    resid.best.arma = arima(djo.lm.resid, order = best.order)
    best.aic = fit.aic
  }}
best.order
best.aic
#The best order is (0,0,2)
resid.best.arma

resid.best.arma.pred = predict(resid.best.arma, n.ahead = 12)
resid.best.arma.pred$pred

djo.pred <- ts((pred.djo.lm + resid.best.arma.pred$pred), start = c(2020,1), deltat = 1/12, freq = 12)
djo.pred

ts.plot(cbind(djo.pre, djo.pred), lty = c(1,9), col=c("black","red") )
ts.plot(cbind(djo.pre, djo.pred, djo.post), lty = c(1,9,2), col=c("black","red","blue") )
```
